# Generated by Django 3.0.6 on 2020-06-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('consist', models.CharField(max_length=128, verbose_name='Музыкальный состав')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=128, null=True, verbose_name='E-mail')),
                ('text', models.TextField(default='', max_length=1024, verbose_name='Текст')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено?')),
            ],
            options={
                'verbose_name': 'Музыкальная группа',
                'verbose_name_plural': 'Музыкальные группы',
            },
        ),
    ]
