# Generated by Django 3.0.6 on 2020-06-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0002_auto_20200618_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
    ]
