# Generated by Django 3.0.6 on 2020-06-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0003_auto_20200618_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Номер для бронирования',
                'verbose_name_plural': 'Номера для бронирования',
            },
        ),
    ]
