# Generated by Django 3.0.6 on 2020-06-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0007_members_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': 'Участник группы', 'verbose_name_plural': 'Участники групп'},
        ),
        migrations.AddField(
            model_name='members',
            name='nmb',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер участника'),
        ),
    ]
