# Generated by Django 3.0.6 on 2020-06-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0009_auto_20200622_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True, verbose_name='E-mail'),
        ),
    ]
