# Generated by Django 3.0.6 on 2020-06-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0010_auto_20200622_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='text',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='Текст'),
        ),
    ]
