# Generated by Django 3.0.6 on 2020-06-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('email_2', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Стоимость')),
                ('tickets', models.ManyToManyField(related_name='Билеты', to='Payment.Ticket')),
            ],
        ),
    ]
