# Generated by Django 3.0.6 on 2020-06-11 14:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость')),
                ('customer_name', models.CharField(default=None, max_length=64, verbose_name='Имя')),
                ('customer_surname', models.CharField(default=None, max_length=64, verbose_name='Фамилия')),
                ('customer_email', models.EmailField(default=None, max_length=128, verbose_name='Email')),
                ('customer_phone', models.CharField(blank=True, default=None, max_length=48, null=True, verbose_name='Телефон')),
            ],
        ),
        migrations.AlterModelOptions(
            name='paymentmodel',
            options={'verbose_name': 'Билет в заказе', 'verbose_name_plural': 'Билеты в заказе'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='tickets',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='value',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='email_2',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='number',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='surname',
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='nmb',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='ticket',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payment.Ticket', verbose_name='Билет'),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Payment.TicketPay', verbose_name='Заказ'),
        ),
    ]
