# Generated by Django 3.0.6 on 2020-06-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_auto_20200612_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='order',
            field=models.ManyToManyField(blank=True, default=None, to='Payment.TicketPay', verbose_name='Заказ'),
        ),
    ]
