# Generated by Django 3.0.6 on 2020-06-11 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0005_auto_20200612_0324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketpay',
            options={'verbose_name': 'Заказанный билет', 'verbose_name_plural': 'Заказанные билеты'},
        ),
        migrations.AddField(
            model_name='ticketpay',
            name='generated_code',
            field=models.CharField(default=3, max_length=6, unique=True, verbose_name='Персональный ключ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='ticket',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payment.Ticket', verbose_name='Билет'),
        ),
    ]
