# Generated by Django 3.0.6 on 2020-06-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0006_auto_20200612_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpay',
            name='generated_code',
            field=models.CharField(max_length=6, verbose_name='Персональный ключ'),
        ),
    ]
