# Generated by Django 3.0.6 on 2020-06-11 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0008_auto_20200612_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='order',
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='order',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Payment.TicketPay', verbose_name='Заказ'),
        ),
    ]
