# Generated by Django 3.0.6 on 2020-06-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0009_auto_20200612_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='order',
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='order',
            field=models.ManyToManyField(blank=True, default=None, to='Payment.TicketPay', verbose_name='Заказ'),
        ),
    ]
