# Generated by Django 3.0.6 on 2020-06-12 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0011_auto_20200613_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='ticket',
            field=models.ForeignKey(blank=True, default='Билет за 3000 RUB', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payment.Ticket', verbose_name='Билет'),
        ),
    ]
