# Generated by Django 3.0.6 on 2020-06-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0013_auto_20200613_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='nmb',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
