# Generated by Django 3.0.6 on 2020-06-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0014_auto_20200613_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpay',
            name='email',
            field=models.EmailField(default=1, max_length=64, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
