# Generated by Django 3.0.6 on 2020-06-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0015_ticketpay_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpay',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='Оплачено?'),
        ),
    ]
